server:
  port: 8890

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infect_statistic?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: edu.fzu.infect.mapper
  configuration:
    map-underscore-to-camel-case: true
